#spring:
#  thymeleaf:
#    cache: false
#  mvc:
#    static-path-pattern: "/static/**"

spring:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true