drop all objects;
create table goods
(
    id bigint generated by default as identity,
    goods_kind_id integer,
    goods_code varchar(255),
    name varchar(255),
    provider_kind varchar(255),
    provider_code varchar(255),
    provider_name varchar(255),
    supply_price integer,
    stock integer,
    box_detail_count integer,
    min_package_count integer,
    stock_notice_count integer,
    stock_notice_state varchar(255),
    is_deleted integer,
    order_val varchar(255),
    update_date timestamp,
    created_date timestamp
);